### PR TITLE
fix(signal): Remove use of moduleRegistered

### PR DESCRIPTION
**Pull request by christianalfoni**
There was a bug related to running the `moduleRegistered` signal. I am not sure what the reason is but when the signal runs when another signal runs (typically router) the debugger does not display the state correctly.

But it is actually not necessary to run a signal. The initial state can be built straight away, and only have the signals for changes.

I have done a few tests and I believe it is working. It would be great with a review and new deploy :-)

### CODE REVIEW

**Comment by christianalfoni** [comment]
Okay, moved the functions into the services now :) ready for release

**Comment by christianalfoni** [comment]
Actually, it is not a service being imported in the action there, it is a helper function... tried to refactor but I got totally mindblocked... because yeah, it is not a service being imported :) So rather move that `getMedia` to a helper function and import it in action or it stays in the service :) it is `matchMedia` which is the actual service

**Comment by maxfrigge** [comment]
@christianalfoni I have updated the pr to what I had in mind.. it would actually be best to refactor the services structure and group certain services, but I didn't want to break the api.

**Comment by christianalfoni** [comment]
Okay, cool... yeah, lets merge this in then? :)

**Comment by christianalfoni** [comment]
Tested, merging it in

**Pull request merged**
